services:
  jekyll:
    build: .
    command: bundle exec jekyll serve --livereload --force_polling --host 0.0.0.0
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll:cached
      - jekyll_gems:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development

volumes:
  jekyll_gems:
