# .github/workflows/devlog.yml
name: Devlog Generator

on:
  workflow_dispatch:
    inputs:
      since:
        description: 'Startdatum (YYYY-MM-DD), z. B. 2025-03-09'
        required: false
        default: ''
      until:
        description: 'Enddatum (YYYY-MM-DD), z. B. 2025-03-25'
        required: false
        default: ''

jobs:
  generate-devlog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Octiware Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests
          pip install --upgrade openai
      
      - name: Run Devlog Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SINCE_DATE: ${{ github.event.inputs.since }}
          UNTIL_DATE: ${{ github.event.inputs.until }}
        run: |
          python scripts/devlog_script.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add commit_updates/
          git commit -m "Automatisch generierter Devlog"
          git push
