name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Passen Sie dies ggf. an Ihren Hauptbranch an
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: innovationone/octiware:latest  # Ihr Docker-Image
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Jekyll-Build ausführen
        run: jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Artefakt hochladen
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Zu GitHub Pages bereitstellen
        id: deployment
        uses: actions/deploy-pages@v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
